version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: ./config/.env.prod
    container_name: hunter-crud-app
    command: >
      gunicorn huntercrud.wsgi:application
        --bind 0.0.0.0:8000
        --workers 4
        --threads 8
        --timeout 300
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

  caddy:
    image: caddy:2-alpine
    env_file: ./config/.env.prod
    container_name: hunter-crud-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  media_volume:
  caddy_data: