on:
  push:
    branches:
      - main

name: Deploy to Server

jobs:

  main-deploy:
    if: github.ref == 'refs/heads/main'
    name: 🚀 Deploy to main server
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v3

      - name: 📁 Copy entire repo to VPS via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: 22
          source: "."
          target: ${{ secrets.REMOTE_APP_PATH }}

      - name: 🔑 SSH & rebuild on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: 22
          script: |
            set -e
            cd ${{ secrets.REMOTE_APP_PATH }}
            echo "⏳ Pulling latest images & rebuilding with prod compose…"
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build

